// SPDX-License-Identifier: GPL-3.0-or-later

package io.github.muntashirakon.io

abstract class PathContentInfo protected constructor(
    /**
     * Returns the short name of the content either from the content-type or extracted from the message. If the
     * content-type is known then this is a specific name string. Otherwise, this is usually the first word of the
     * message generated by the magic file.
     */
    val name: String,
    /**
     * Returns the full message as generated by the magic matching code or null if none. This should be similar to the
     * output from the Unix file(1) command.
     */
    val message: String?,
    /**
     * Returns the mime-type or null if none.
     */
    val mimeType: String?,
    /**
     * Returns an array of associated file-extensions or null if none.
     */
    val fileExtensions: Array<String>?,
    /**
     * Whether this was a partial match. For some types, there is a main matching pattern and then more
     * specific patterns which detect additional features of the type. A partial match means that none of the more
     * specific patterns fully matched the content. It's probably still of the type but just not a variant that the
     * entries from the magic file(s) know about.
     */
    val isPartial: Boolean
) {
    companion object {
        val TAG: String = PathContentInfo::class.java.simpleName
    }
}
